export const DWACTIVESKILL_OPTIONS = [
  "=",
  "II_CHR_SYS_SCR_ACTIVITION",
  "II_CHR_SYS_SCR_UPCUTSTONE",
  "II_SYS_SYS_SCR_BLESSING",
  "II_SYS_SYS_SCR_RECCURENCE",
  "SI_GEN_ATKSPELL_RATESINGLE",
  "SI_GEN_BUFFBREAK",
  "SI_GEN_BUFFBREAK_X",
  "SI_GEN_KNOCK_BACK",
  "SI_GEN_POISONSTING",
  "SI_GEN_STONEHAND",
  "SI_GEN_STUNGROUP",
  "SI_GEN_SWORDCROSS",
  "SI_GEN_TG_BUFF_01",
  "SI_MAG_EARTH_LOOTING",
  "SI_MOB_BLEEDING"
];
