export const DWWEAPONTYPE_OPTIONS = [
  "=",
  "WI_DUNGEON_DA_DK",
  "WI_DUNGEON_VOLCANE",
  "WI_WORLD_MADRIGAL",
  "WT_MAGIC_WAND",
  "WT_MELEE",
  "WT_MELEE_AXE",
  "WT_MELEE_KNUCKLE",
  "WT_MELEE_STAFF",
  "WT_MELEE_STICK",
  "WT_MELEE_SWD",
  "WT_MELEE_YOYO",
  "WT_RANGE",
  "WT_RANGE_BOW"
];
