// Monster AI options for dwai field
export const MONSTERS_DWAI_OPTIONS = [
  "AII_AGGRO_NORMAL",
  "AII_ARENA_REAPER",
  "AII_BEAR",
  "AII_BIGMUSCLE",
  "AII_BUFF_HELPER",
  "AII_BUFF_HELPER_RM",
  "AII_BUFF_HELPER_SERAPH",
  "AII_CLOCKWORKS",
  "AII_EGG",
  "AII_KRRR",
  "AII_METEONYKER",
  "AII_MONSTER",
  "AII_MOVER",
  "AII_NONE",
  "AII_PARTY_AGGRO_LEADER",
  "AII_PARTY_AGGRO_SUB",
  "AII_PET"
];
