export const SETS_ELEM_PART_OPTIONS = [
  "PARTS_EARRING2",
  "PARTS_CAP",
  "PARTS_MASK",
  "PARTS_EARRING1",
  "PARTS_GLOVE",
  "PARTS_UPPER_BODY",
  "PARTS_RING1",
  "PARTS_HAT",
  "PARTS_FOOT",
  "PARTS_RING2",
  "PARTS_BOOTS",
  "PARTS_CLOAK",
  "PARTS_CLOTH",
  "PARTS_HAND",
  "PARTS_NECKLACE1"
];
