export const SKILLS_DWEXETARGET_OPTIONS = [
  "EXT_ANOTHER",
  "EXT_ANOTHERWITH",
  "EXT_MAGIC",
  "EXT_MAGICATK",
  "EXT_MAGICATKSHOT",
  "EXT_MELEEATK",
  "EXT_OBJCHGPARAMET",
  "EXT_SELFCHGPARAMET",
  "EXT_TROUPE",
  "EXT_TROUPEWITH"
];
