export const SKILLS_DWSFXOBJ5_OPTIONS = [
  "=",
  "XI_SKILL_BIL_KNU_ASALRAALAIKUM01",
  "XI_SKILL_BIL_KNU_BGVURTIALBOLD01",
  "XI_SKILL_BLD_DOUBLESW_BLADEDANCE03",
  "XI_SKILL_GEN_FLASH",
  "XI_SKILL_KNT_TWO_POWERSWING02",
  "XI_SKILL_LORDK_HOLYARMOR02",
  "XI_SKILL_STORM_STORMBLASTE04",
  "XI_SLAYER_SUPREMEEXPLO",
  "XI_SLAYER_TEMPORADA05"
];
