export const SKILLS_DWLINKKIND_OPTIONS = [
  "=",
  "IK3_AXE",
  "IK3_BOW",
  "IK3_CHEERSTICK",
  "IK3_ENCHANTWEAPON",
  "IK3_KNUCKLEHAMMER",
  "IK3_MAGICBARUNA",
  "IK3_MAGICBOTH",
  "IK3_SHIELD",
  "IK3_STAFF",
  "IK3_SWD",
  "IK3_WAND",
  "IK3_YOBO",
  "IK3_YOYO",
  "IK3_ZEMBARUNA"
];
