export const SKILLS_DWRESKILL2_OPTIONS = [
  "=",
  "SI_BIL_PST_BGVURTIALBOLD",
  "SI_ELE_EARTH_EARTHQUAKE",
  "SI_ELE_ELECTRICITY_ELETRICSHOCK",
  "SI_JST_YOYO_BACKSTAB",
  "SI_PSY_PSY_MAXIMUMCRISIS",
  "SI_PSY_PSY_SPRITBOMB",
  "SI_RAG_BOW_PIRCINGARROW",
  "SI_RIN_SUP_SPIRITUREFORTUNE"
];
